version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg-container
    restart: always
    environment:
      POSTGRES_DB: deep-origin-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
